---
# Source: tvdb/templates/app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tvdb-app
  namespace: tvdb
type: Opaque
stringData:
  api-token: "1234567"
  admin-username: "admin"
  admin-password: "admin"
---
# Source: tvdb/templates/storage-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tvdb-storage
  namespace: tvdb
type: Opaque
stringData:
  mysql-root-password: "admin"
---
# Source: tvdb/templates/storage-pv.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvdb-storage-pvc
  namespace: tvdb
  labels:
    app: tvdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
# Source: tvdb/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tvdb-app
  namespace: tvdb
  labels:
    app: tvdb
    tier: app
spec:
  type: ClusterIP
  ports:
  - name: tvdb-app-port
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: tvdb
---
# Source: tvdb/templates/storage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tvdb-database
  namespace: tvdb
  labels:
    app: tvdb
    tier: storage
spec:
  type: ClusterIP
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: tvdb
---
# Source: tvdb/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-app-deployment
  namespace: tvdb
  labels:
    app: tvdb
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
        tier: app
      annotations:
        checksum/app-secret: 394ff03bdc15443076fa69ab40d2c24f8f76acea12925acf56907f6c66bf824e
        checksum/storage-secret: 12a4ef02c558beccd6565c64092727d2a70c28b3f3c62313943a5dda126f83ef
    spec:
      restartPolicy: "Always"
      initContainers:
      - name: wait-for-storage
        image: busybox:1.36.1
        command: ['sh', '-c', 'until nc -zv tvdb-database 3306; do echo waiting for database; sleep 2; done']
      containers:
      - name: tvdb-app
        image: ravelox/tvdb:1.8.0.14
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: tvdb-database
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tvdb-storage
              key: mysql-root-password
        - name: DB_NAME
          value: tvdb
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: tvdb-app
              key: api-token
              optional: true
        - name: ENABLE_ADMIN_UI
          value: "false"
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: tvdb-app
              key: admin-username
              optional: true
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tvdb-app
              key: admin-password
              optional: true
---
# Source: tvdb/templates/storage-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-storage-deployment
  namespace: tvdb
  labels:
    app: tvdb
    tier: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
        tier: storage
    spec:
      restartPolicy: "Always"
      initContainers:
        - name: remove-lostfound
          image: busybox
          command: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: tvdb-storage-volume
              mountPath: /var/lib/mysql
      containers:
      - image: mysql:8.0.36
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tvdb-storage
              key: mysql-root-password
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: tvdb-storage-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: tvdb-storage-volume
        persistentVolumeClaim:
          claimName: tvdb-storage-pvc
