services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin 
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3336:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "6888:80"
  tvdb:
    image: ravelox/tvdb:1.0.1
    restart: always
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: tvdb
volumes:
  mysql-data:
