services:
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD must be set}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3336:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_ROOT_USER:-root}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD must be set}
    ports:
      - "6888:80"
  tvdb:
    image: ${TVDB_IMAGE:-ravelox/tvdb:1.4.1}
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-20.12.2-slim}
        APP_VERSION: ${APP_VERSION:-1.4.1}
        BUILD_NUMBER: ${BUILD_NUMBER:-0}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set}
      DB_NAME: ${DB_NAME:-tvdb}
      API_TOKEN: ${API_TOKEN:-}
      ENABLE_ADMIN_UI: ${ENABLE_ADMIN_UI:-true}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
volumes:
  mysql-data:
