apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-app-deployment
  namespace: tvdb
  labels:
    app: tvdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
    spec:
      containers:
      - name: tvdb-app
        image: ravelox/tvdb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: tvdb-database
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: admin
        - name: DB_NAME
          value: tvdb
