apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-storage-deployment
  labels:
    app: tvdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
    spec:
      containers:
      - image: mysql:8.0
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: tvdb-storage-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: tvdb-storage-volume
        persistentVolumeClaim:
          claimName: tvdb-storage-pvc
