apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-app-deployment
  labels:
    app: tvdb
spec:
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
    spec:
      containers:
      - name: tvdb-app
        image: ravelox/tvdb:1.0.0
        ports:
        - containerPort: 3000
        env:
        # - name: CONFIG_SETTING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: my-configmap
        #       key: setting-value
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: tvdb-database
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: admin
        - name: DB_NAME
          value: tvdb
