apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvdb-app-deployment
  namespace: tvdb
  labels:
    app: tvdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvdb
  template:
    metadata:
      labels:
        app: tvdb
    spec:
      initContainers:
      - name: wait-for-storage
        image: busybox:1.36.1
        command: ['sh', '-c', 'until nc -zv tvdb-database 3306; do echo waiting for database; sleep 2; done']
      containers:
      - name: tvdb-app
        image: ravelox/tvdb:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: tvdb-database
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tvdb-db-credentials
              key: mysql-root-password
        - name: DB_NAME
          value: tvdb
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: tvdb-db-credentials
              key: api-token
              optional: true
        - name: ENABLE_ADMIN_UI
          value: "false"
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: tvdb-db-credentials
              key: admin-username
              optional: true
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tvdb-db-credentials
              key: admin-password
              optional: true
