apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvdb-storage-pvc
  namespace: tvdb
  labels:
    app: tvdb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 500Mi
