apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvdb-storage-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    #
    # Change this to point to a directory that's available
    # on all nodes (something mounted to all of them)
    #
    path: /vagrant/data/postgresql
    type: DirectoryOrCreate
