{{- if and (not .Values.app.existingSecret) (or .Values.app.apiToken .Values.app.adminUsername .Values.app.adminPassword) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tvdb.appSecretName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if .Values.app.apiToken }}
  {{ .Values.app.apiTokenKey }}: {{ .Values.app.apiToken | quote }}
  {{- end }}
  {{- if .Values.app.adminUsername }}
  {{ .Values.app.adminUsernameKey }}: {{ .Values.app.adminUsername | quote }}
  {{- end }}
  {{- if .Values.app.adminPassword }}
  {{ .Values.app.adminPasswordKey }}: {{ .Values.app.adminPassword | quote }}
  {{- end }}
{{- end -}}
