apiVersion: v1
kind: Service
metadata:
  name: tvdb-app
  namespace: {{ .Values.namespace }}
  labels:
    app: tvdb
    tier: app
spec:
  type: ClusterIP
  ports:
  - name: tvdb-app-port
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: tvdb
