apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvdb-storage-pv
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.volume.storage }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.storage.volume.hostPath | quote }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvdb-storage-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: tvdb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.storage.volume.storage }}
