apiVersion: v1
kind: Service
metadata:
  name: tvdb-database
  namespace: {{ .Values.namespace }}
  labels:
    app: tvdb
spec:
  type: ClusterIP
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: tvdb
