apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvdb-storage-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: tvdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.volume.storage }}
